// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCktPS4r-EKoVJAsRVLFc8l3OChZO3Xbz8",
    authDomain: "finlit-616d8.firebaseapp.com",
    projectId: "finlit-616d8",
    storageBucket: "finlit-616d8.firebasestorage.app",
    messagingSenderId: "768641326836",
    appId: "1:768641326836:web:727d4461d754e5474908a1",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsEM4aa1FfZ4E0QdsbcXEC-Zx_P1_rcg0',
    appId: '1:768641326836:android:56581d4e9f04c8cc4908a1',
    messagingSenderId: '768641326836',
    projectId: 'finlit-616d8',
    storageBucket: 'finlit-616d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9DDNpt6Cg11cTCjLVXwb3cah4XTQKRWM',
    appId: '1:768641326836:ios:690d8a068e464e004908a1',
    messagingSenderId: '768641326836',
    projectId: 'finlit-616d8',
    storageBucket: 'finlit-616d8.firebasestorage.app',
    iosClientId:
        '768641326836-iiirjg5mo6ju8n81at5cq4s53aeq90fb.apps.googleusercontent.com',
    iosBundleId: 'com.finlit.main',
  );
}
